name: GitHub Grass Miner 🌱

on:
  schedule:
    - cron: "0 11 * * *"  # Runs daily at 1 AM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Log File
        run: |
          echo "$(date) - Auto commit by GitHub Grass Miner" >> log.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add log.txt
          git commit -m "chore: automated commit 🌱"
          git push
