name: Generate Contribution Snake
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: tosinchukwu
          svg_out_path: dist/github-contribution-grid-snake.svg
